version: "3.7"
services:

  front-envoy:
    build:
      context: ./front-envoy-proxy
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "8000:80"
      - "8001:8001"
      - "8443:443"

  service1:
    build:
      context: ./simpleexpressapi1
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - service1
    expose:
      - "80"

  service2:
    build:
      context: ./simpleexpressapi2
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - service2
    expose:
      - "80"

networks:
  envoymesh: {}