apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: front-envoy-proxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: front-envoy-proxy
    spec:
      serviceAccountName: frontenvoysa
      containers:
      - name: front-envoy-proxy
        image: dockershome/simplefrontenvoy
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}