apiVersion: v1
kind: Service
metadata:
  name: front-envoy-service
spec:
  type: LoadBalancer
  selector:
    service: front-envoy-proxy
  ports:
  - name: front-envoy
    port: 80
    targetPort: 80
  - name: front-envoy-admin
    port: 8001
    targetPort: 8001
